-- Generated by tools/gen_loot.py from PhoenixXI 5b1282e9 2026-09-26 (live). Do not edit; run the script again.
return {
zone = 129,
mobs = {
[17305666]={t='Serket'},
[17305667]={t='Lambton_Worm'},
},
templates = {
['Lambton_Worm']={nm=false,script=false,drops={{r=240,i=11285},{r=240,i=16275},{r=240,i=16344},{r=240,i=17751},{r=150,i=909},{r=150,i=901},{r=150,i=836}},steal={}},
['Serket']={nm=true,script=false,drops={{r=10,i=4175},{r=10,i=4173},{r=240,i=11287},{r=240,i=19213},{r=10,i=12348},{r=10,i=13552},{r=10,i=16767},{r=10,i=901}},steal={}},
},
prices = {[836]=5000,[901]=5000,[909]=6978,[4173]=false,[4175]=false,[11285]=5200,[11287]=11731,[12348]=5600,[13552]=4375,[16275]=4339,[16344]=0,[16767]=6737,[17751]=4600,[19213]=778},
}
