-- Generated by tools/gen_loot.py from PhoenixXI 5b1282e9 2026-09-26 (live). Do not edit; run the script again.
return {
zone = 144,
mobs = {
[17367077]={t='Maat_thf',lv={70,70}},
[17367078]={t='Maat_thf',lv={70,70}},
[17367079]={t='Maat_thf',lv={70,70}},
},
templates = {
['Maat_thf']={nm=true,script=false,drops={},steal={4181}},
},
prices = {[4181]=false},
}
