-- Generated by tools/gen_loot.py from PhoenixXI 5b1282e9 2026-09-26 (live). Do not edit; run the script again.
return {
zone = 146,
mobs = {
[17375426]={t='Queen_of_Cups',lv={75,75}},
[17375427]={t='Queen_of_Batons',lv={75,75}},
[17375433]={t='Queen_of_Cups',lv={75,75}},
[17375434]={t='Queen_of_Batons',lv={75,75}},
[17375440]={t='Queen_of_Cups',lv={75,75}},
[17375441]={t='Queen_of_Batons',lv={75,75}},
},
templates = {
['Queen_of_Batons']={nm=true,script=false,drops={{r=100,i=984}},steal={}},
['Queen_of_Cups']={nm=true,script=false,drops={{r=100,i=971}},steal={}},
},
prices = {[971]=918,[984]=918},
}
