-- Generated by tools/gen_loot.py from PhoenixXI 5b1282e9 2026-09-26 (live). Do not edit; run the script again.
return {
zone = 170,
mobs = {
[17473540]={t='Ace_of_Cups_Large',lv={73,75}},
[17473541]={t='Ace_of_Batons_Large',lv={73,75}},
[17473542]={t='Ace_of_Swords_Large',lv={73,75}},
[17473543]={t='Ace_of_Coins_Large',lv={73,75}},
[17473546]={t='Ace_of_Cups',lv={73,75}},
[17473547]={t='Ace_of_Batons',lv={73,75}},
[17473548]={t='Ace_of_Swords',lv={73,75}},
[17473549]={t='Ace_of_Coins',lv={73,75}},
[17473552]={t='Ace_of_Cups',lv={73,75}},
[17473553]={t='Ace_of_Batons',lv={73,75}},
[17473554]={t='Ace_of_Swords',lv={73,75}},
[17473555]={t='Ace_of_Coins',lv={73,75}},
},
templates = {
['Ace_of_Batons']={nm=true,script=false,drops={{r=10,i=973}},steal={}},
['Ace_of_Batons_Large']={nm=true,script=false,drops={{r=10,i=973}},steal={}},
['Ace_of_Coins']={nm=true,script=false,drops={{r=10,i=999}},steal={}},
['Ace_of_Coins_Large']={nm=true,script=false,drops={{r=10,i=999}},steal={}},
['Ace_of_Cups']={nm=true,script=false,drops={{r=10,i=960}},steal={}},
['Ace_of_Cups_Large']={nm=true,script=false,drops={{r=10,i=960}},steal={}},
['Ace_of_Swords']={nm=true,script=false,drops={{r=10,i=986}},steal={}},
['Ace_of_Swords_Large']={nm=true,script=false,drops={{r=10,i=986}},steal={}},
},
prices = {[960]=1164,[973]=1164,[986]=1164,[999]=1200},
}
