-- Generated by tools/gen_loot.py from PhoenixXI 5b1282e9 2026-09-26 (live). Do not edit; run the script again.
return {
zone = 19,
mobs = {
[16855059]={t='Neosatiator',lv={30,30}},
[16855065]={t='Neosatiator',lv={30,30}},
[16855071]={t='Neosatiator',lv={30,30}},
},
templates = {
['Neosatiator']={nm=false,script=false,drops={{r=1000,i=4374},{r=150,i=4373},{r=50,i=1040},{r=50,i=4375},{r=150,i=1089}},steal={4374}},
},
prices = {[1040]=false,[1089]=false,[4373]=241,[4374]=25,[4375]=640},
}
