-- Generated by tools/gen_loot.py from PhoenixXI 5b1282e9 2026-09-26 (live). Do not edit; run the script again.
return {
zone = 32,
mobs = {
[16908289]={t='Mammet-22_Zeta',lv={55,56}},
[16908290]={t='Mammet-22_Zeta',lv={55,56}},
[16908291]={t='Mammet-22_Zeta',lv={55,56}},
[16908292]={t='Mammet-22_Zeta',lv={55,56}},
[16908293]={t='Mammet-22_Zeta',lv={55,56}},
[16908296]={t='Mammet-22_Zeta',lv={55,56}},
[16908297]={t='Mammet-22_Zeta',lv={55,56}},
[16908298]={t='Mammet-22_Zeta',lv={55,56}},
[16908299]={t='Mammet-22_Zeta',lv={55,56}},
[16908300]={t='Mammet-22_Zeta',lv={55,56}},
[16908303]={t='Mammet-22_Zeta',lv={55,56}},
[16908304]={t='Mammet-22_Zeta',lv={55,56}},
[16908305]={t='Mammet-22_Zeta',lv={55,56}},
[16908306]={t='Mammet-22_Zeta',lv={55,56}},
[16908307]={t='Mammet-22_Zeta',lv={55,56}},
},
templates = {
['Mammet-22_Zeta']={nm=true,script=false,drops={{r=240,i=5264},{r=150,i=5264}},steal={}},
},
prices = {[5264]=1},
}
