-- Generated by tools/gen_loot.py from PhoenixXI 5b1282e9 2026-09-26 (live). Do not edit; run the script again.
return {
zone = 57,
mobs = {
[17010689]={t='Wootzshell_fished',lv={73,74}},
[17010693]={t='Llamhigyn_Y_Dwr',lv={77,79}},
[17010694]={t='Giant_Orobon',lv={79,80}},
},
templates = {
['Giant_Orobon']={nm=false,script=true,drops={{r=50,i=5563}},steal={}},
['Llamhigyn_Y_Dwr']={nm=false,script=false,drops={{r=150,i=940},{r=100,i=849}},steal={}},
['Wootzshell_fished']={nm=false,script=false,drops={{r=150,i=4400},{r=100,i=881},{r=50,i=1889},{r=10,i=1193}},steal={}},
},
prices = {[849]=800,[881]=383,[940]=52,[1193]=3325,[1889]=258,[4400]=280,[5563]=280},
}
