-- Generated by tools/gen_loot.py from PhoenixXI 5b1282e9 2026-09-26 (live). Do not edit; run the script again.
return {
zone = 86,
mobs = {
[17129519]={t='King_Arthro'},
[17129532]={t='Lambton_Worm'},
},
templates = {
['King_Arthro']={nm=true,script=false,drops={{r=240,i=16178},{r=240,i=11286},{r=50,i=836},{r=50,i=12924},{r=50,i=15899}},steal={}},
['Lambton_Worm']={nm=false,script=false,drops={{r=240,i=11285},{r=240,i=16275},{r=240,i=16344},{r=240,i=17751},{r=150,i=909},{r=150,i=901},{r=150,i=836}},steal={}},
},
prices = {[836]=5000,[901]=5000,[909]=6978,[11285]=5200,[11286]=2862,[12924]=7520,[15899]=false,[16178]=2130,[16275]=4339,[16344]=0,[17751]=4600},
}
