-- Generated by tools/gen_loot.py from PhoenixXI 5b1282e9 2026-09-26 (live). Do not edit; run the script again.
return {
zone = 87,
mobs = {
[17133885]={t='Boodlix',lv={75,80}},
},
templates = {
['Boodlix']={nm=false,script=false,drops={{r=100,i=16375}},steal={}},
},
prices = {[16375]=false},
}
