-- Generated by tools/gen_loot.py from PhoenixXI 5b1282e9 2026-09-26 (live). Do not edit; run the script again.
return {
zone = 93,
mobs = {
[17158202]={t='Guivre'},
[17158203]={t='Lambton_Worm'},
},
templates = {
['Guivre']={nm=true,script=false,drops={{r=1000,i=909},{r=150,i=11288},{r=150,i=19212}},steal={}},
['Lambton_Worm']={nm=false,script=false,drops={{r=240,i=11285},{r=240,i=16275},{r=240,i=16344},{r=240,i=17751},{r=150,i=909},{r=150,i=901},{r=150,i=836}},steal={}},
},
prices = {[836]=5000,[901]=5000,[909]=6978,[11285]=5200,[11288]=11731,[16275]=4339,[16344]=0,[17751]=4600,[19212]=778},
}
